import type { Tenant } from "@/lib/tenant-types";

export const glieres: Tenant = {
  id: "glieres",
  name: "Auto-École des Glières",
  shortName: "Les Glières",
  domain: "auto-ecole-glieres.fr",
  founded: 2017,

  address: "33 rue des Glières, 74100 Annemasse",
  street: "33 rue des Glières",
  city: "Annemasse",
  postalCode: "74100",
  region: "Haute-Savoie",
  country: "France",
  phone: "04 50 92 24 01",
  phoneIntl: "+33450922401",
  email: "secretariat@auto-ecole-glieres.fr",
  emailLegacy: "secretariat.les.glieres@gmail.com",
  geo: { lat: 46.1953, lng: 6.2392 },

  hours: {
    monday: ["14:00-18:00"],
    tuesday: ["14:00-18:00"],
    wednesday: ["10:00-13:00", "14:00-18:00"],
    thursday: ["14:00-18:00"],
    friday: ["10:00-13:00", "14:00-18:00"],
    saturday: ["09:00-12:00"],
    sunday: [],
  },

  rating: 4.8,
  ratingCount: 412,
  studentsTrained: 1350,
  successRateFirstAttempt: 75,
  positiveEvaluation: 96,
  qualiopi: true,
  cpfEligible: true,
  permisAUnEuro: true,

  brand: {
    mode: "light",
    accent: "#FF5A36",
    accentName: "orange-corail",
    logo: { monogram: "G", wordmark: "Auto-École", sub: "Les Glières" },
  },

  copy: {
    heroBadge: "Nouveau 2026",
    heroBadgeSecondary: "Permis Moto A2 disponible",
    heroTitleLine1: "Le permis,",
    heroTitleLine2: "version sérieuse",
    heroSubtitle:
      "Permis B, boîte auto, conduite accompagnée, moto A2 et code en ligne à __CITY__. Une équipe humaine, du matériel récent, des tarifs honnêtes — et __SUCCESS__% de réussite au premier passage.",
    statsTitle: "Une auto-école qui livre la marchandise.",
    aboutIntro:
      "Créée en __FOUNDED__ par Vincent à __CITY__, l'Auto-École des Glières est née d'un constat simple : on peut faire passer le permis sans traiter les élèves comme des numéros. Sept ans plus tard, on continue.",
    finalCtaBadge: "🎯 Plus que quelques places ce mois-ci",
  },

  services: [
    {
      slug: "permis-b", name: "Permis B",
      short: "La voiture, version classique. Boîte manuelle, autoroute incluse.",
      icon: "Car", ageMin: 17, duration: "3 à 6 mois en moyenne",
      hourPrice: 70, packagePrice: 1490, hours: 20,
      cpfEligible: true, oneEuroDay: true, acceleratedAvailable: true,
      highlights: ["Forfait 20h dès 1 490 €", "Boîte manuelle, voiture récente", "Examens blancs réguliers", "Suivi pédagogique digital"],
      description: "La formation classique sur boîte manuelle, qui te donne accès à toutes les voitures du monde. On t'accompagne du livret au jour J de l'examen, sans surprise sur la facture.",
      programme: [
        { title: "1. Maîtriser le maniement du véhicule", items: ["Découvrir les commandes, démarrages, arrêts", "Diriger la voiture en avant et en arrière", "Régulation de l'allure"] },
        { title: "2. Appréhender la route", items: ["Routes à chaussée séparée, intersections", "Communication entre usagers", "Choisir sa position sur la chaussée"] },
        { title: "3. Circuler dans des situations difficiles", items: ["Circulation en ville, hors agglomération", "Conduite de nuit, sur autoroute", "Conditions météo dégradées"] },
        { title: "4. Pratiquer une conduite autonome, sûre et économique", items: ["Anticiper, partager la route", "Économiser le carburant", "Préparer un trajet, gérer la fatigue"] },
      ],
    },
    {
      slug: "permis-boite-automatique", name: "Permis boîte automatique",
      short: "Plus court, plus simple, accessible dès 13h de conduite.",
      icon: "Cog", ageMin: 17, duration: "2 à 4 mois",
      hourPrice: 70, packagePrice: 1390, hours: 13,
      cpfEligible: true, oneEuroDay: true,
      highlights: ["Forfait dès 1 390 €", "Minimum légal 13h (vs 20h)", "Idéal pour passer plus vite", "Passerelle vers manuelle possible"],
      description: "Le permis BEA — boîte automatique — c'est la voie express. Formation plus courte, examen identique, et tu peux toujours basculer sur boîte manuelle plus tard via la passerelle (7h seulement).",
      programme: [
        { title: "1. Prise en main véhicule automatique", items: ["Pédales, sélecteur, parking brake", "Démarrages en côte", "Manœuvres de base"] },
        { title: "2. Circulation urbaine et inter-urbaine", items: ["Trajectoires, intersections", "Lecture de panneaux", "Gestion des angles morts"] },
        { title: "3. Conditions difficiles", items: ["Pluie, nuit, autoroute", "Trafic dense", "Stationnement avancé"] },
        { title: "4. Autonomie & éco-conduite", items: ["Trajets longs", "Anticipation", "Conduite économique"] },
      ],
    },
    {
      slug: "permis-moto-a2", name: "Permis Moto A2",
      short: "Nouveauté 2026 chez nous. La moto bridée 35 kW dès 18 ans.",
      icon: "Bike", isNew: true, year: 2026, ageMin: 18, duration: "1 à 3 mois",
      hourPrice: 75, packagePrice: 1290, hours: 20,
      cpfEligible: true,
      highlights: ["Nouveau dès 2026", "Plateau + circulation", "Équipement fourni pour l'examen", "Moto récente bridée"],
      description: "Le permis A2, c'est la moto pour de vrai : machines bridées à 35 kW, accessibles dès 18 ans. Formation complète plateau + circulation, et après 2 ans tu passes en A sans repasser l'examen.",
      programme: [
        { title: "1. Maîtrise de la moto à allure réduite", items: ["Maniabilité plateau", "Évitement, freinage", "Démarrage en côte"] },
        { title: "2. Plateau allure normale", items: ["Slalom, lent et rapide", "Freinage d'urgence", "Évitement obstacle"] },
        { title: "3. Circulation", items: ["Trajectoires moto", "Gestion intersections", "Trafic dense"] },
        { title: "4. Autonomie", items: ["Trajet long", "Météo dégradée", "Conduite défensive"] },
      ],
    },
    {
      slug: "conduite-accompagnee", name: "Conduite accompagnée (AAC)",
      short: "Dès 15 ans. La meilleure stat de réussite en France.",
      icon: "Users", ageMin: 15, duration: "1 à 3 ans selon âge",
      hourPrice: 70, packagePrice: 1590, hours: 20,
      cpfEligible: true, oneEuroDay: true,
      highlights: ["Démarre dès 15 ans", "Permis dès 17 ans", "Réussite 1er passage : 88%", "Période probatoire réduite"],
      description: "L'AAC, c'est l'assurance d'un permis solide. Tu commences ta formation dès 15 ans, tu passes le code, puis tu roules avec un accompagnateur pendant minimum 1 an et 3 000 km. Résultat : 88% de réussite au premier coup.",
      programme: [
        { title: "1. Formation initiale (20h)", items: ["Apprentissage avec moniteur", "4 compétences REMC", "Évaluation finale"] },
        { title: "2. Rendez-vous préalable (2h)", items: ["Bilan avec ton accompagnateur", "Mise en situation", "Documents officiels"] },
        { title: "3. Phase accompagnée", items: ["1 an minimum, 3 000 km", "Trajets variés", "Carnet d'apprentissage"] },
        { title: "4. RDV pédagogiques (2x2h)", items: ["Bilan à mi-parcours", "Bilan final avant examen"] },
      ],
    },
    {
      slug: "conduite-supervisee", name: "Conduite supervisée",
      short: "Échec à l'examen ou besoin de plus de pratique ? Repasse en mode supervisé.",
      icon: "ShieldCheck", ageMin: 18, duration: "Variable",
      hourPrice: 70, cpfEligible: false,
      highlights: ["Après un échec ou par choix", "Roule avec un accompagnateur", "Repasse l'examen en confiance", "1 000 km minimum"],
      description: "La supervisée, c'est l'option maline si tu as raté la conduite ou si tu veux te muscler avant le passage. Tu roules avec un accompagnateur entre l'évaluation et l'examen, sans pression de timing.",
      programme: [
        { title: "1. Évaluation préalable", items: ["Bilan compétences", "Validation par le moniteur"] },
        { title: "2. Phase supervisée", items: ["1 000 km minimum", "Trajets variés", "Tu choisis quand passer l'examen"] },
        { title: "3. Examen pratique", items: ["Préparation finale", "Examen en conditions réelles"] },
      ],
    },
    {
      slug: "code-de-la-route", name: "Code de la route",
      short: "Cours en salle + entraînement en ligne illimité.",
      icon: "BookOpen", ageMin: 15, duration: "1 à 3 mois",
      packagePrice: 290, cpfEligible: true,
      highlights: ["Forfait 6 mois à 290 €", "Cours en salle + plateforme web", "+ de 1 000 questions officielles", "Examen sur place"],
      description: "Le code, c'est la base. On te file un accès illimité à notre plateforme en ligne (web et mobile), des cours en salle réguliers, et on t'inscrit à l'examen quand t'es prêt. Pas avant.",
      programme: [
        { title: "Les 10 thèmes officiels", items: ["Circulation routière", "Conducteur", "Route", "Autres usagers", "Notions diverses", "Premiers secours", "Mécanique", "Sécurité passagers", "Environnement", "Réglementation"] },
        { title: "Méthode", items: ["Quiz quotidien recommandé", "Examens blancs hebdomadaires", "Cours en salle 2x/semaine"] },
      ],
    },
    {
      slug: "permis-am", name: "Permis AM (cyclomoteur)",
      short: "Le BSR nouvelle formule, dès 14 ans. 8h de formation.",
      icon: "Zap", ageMin: 14, duration: "8 heures sur 2 jours",
      packagePrice: 290, cpfEligible: false,
      highlights: ["Dès 14 ans", "8h de formation", "Pour scooter & quadricycle", "Forfait à 290 €"],
      description: "Anciennement BSR, le permis AM permet de conduire un scooter 50 cm³ ou un quadricycle léger dès 14 ans. Formation rapide en 2 demi-journées, et tu pars rouler.",
      programme: [
        { title: "Théorie (2h)", items: ["Sécurité routière", "Équipement", "Réglementation"] },
        { title: "Plateau (3h)", items: ["Maniement", "Freinage", "Trajectoires"] },
        { title: "Circulation (3h)", items: ["Trafic réel", "Intersections", "Conduite défensive"] },
      ],
    },
    {
      slug: "passerelle", name: "Passerelle boîte auto → manuelle",
      short: "Tu as le BEA ? 7h de formation et tu passes sur boîte manuelle.",
      icon: "ArrowLeftRight", ageMin: 18, duration: "7 heures",
      packagePrice: 490, cpfEligible: true,
      highlights: ["7h de formation seulement", "Pas d'examen à repasser", "Forfait à 490 €", "Disponible dès 3 mois après le BEA"],
      description: "Tu as le permis boîte auto et tu veux conduire toutes les voitures ? La passerelle est faite pour ça. 7h de formation, pas d'examen, juste une attestation et c'est plié.",
      programme: [
        { title: "Module unique 7h", items: ["Embrayage et boîte de vitesses", "Démarrages en côte", "Circulation manuelle", "Attestation finale"] },
      ],
    },
  ],

  packages: [
    { slug: "permisB20h", label: "Permis B — Forfait 20h", price: 1490, hours: 20,
      includes: ["Code en ligne 6 mois", "20h de conduite", "Frais de présentation à l'examen", "Livret numérique"], popular: true },
    { slug: "permisB30h", label: "Permis B — Forfait 30h", price: 2150, hours: 30,
      includes: ["Code en ligne 12 mois", "30h de conduite", "2 examens blancs", "Frais d'inscription préfecture", "Livret numérique"] },
    { slug: "permisBAccelere", label: "Permis B accéléré (4 sem.)", price: 1990, hours: 20,
      includes: ["Code intensif 1 mois", "20h de conduite en 4 semaines", "Examens prioritaires", "Suivi quotidien"], tag: "Express" },
    { slug: "permisAuto", label: "Permis boîte automatique 13h", price: 1390, hours: 13,
      includes: ["Code en ligne 6 mois", "13h de conduite (minimum légal)", "Frais de présentation"] },
    { slug: "permisAAC", label: "Conduite accompagnée — Forfait", price: 1590, hours: 20,
      includes: ["Code en ligne 12 mois", "20h de conduite", "RDV préalable accompagnateur", "2 RDV pédagogiques"] },
    { slug: "permisMotoA2", label: "Permis Moto A2", price: 1290, hours: 20,
      includes: ["Code moto", "20h de plateau & circulation", "Équipement examen fourni"], tag: "Nouveau" },
    { slug: "code", label: "Code de la route — 6 mois", price: 290,
      includes: ["Accès web & mobile illimité", "Cours en salle 2x/semaine", "Inscription à l'examen"] },
    { slug: "passerelle", label: "Passerelle BEA → manuelle", price: 490, hours: 7,
      includes: ["7h de formation", "Attestation officielle"] },
  ],

  hourlyRates: [
    { key: "standard", price: 70, label: "Heure de conduite — boîte manuelle" },
    { key: "automatic", price: 70, label: "Heure de conduite — boîte automatique" },
    { key: "accelerated", price: 90, label: "Heure de conduite — formation accélérée" },
    { key: "bridge", price: 70, label: "Heure passerelle auto → manuelle" },
    { key: "moto", price: 75, label: "Heure de moto A2" },
  ],

  team: [
    { name: "Vincent", role: "Fondateur & moniteur", bio: "À l'origine de l'auto-école depuis 2017. Spécialiste du permis B et de la moto.", senior: true },
    { name: "Eva", role: "Accueil & secrétariat", bio: "Le sourire à l'accueil, le pilote du planning et des dossiers." },
    { name: "Sylvain", role: "Moniteur permis B", bio: "Pédagogue patient, fan de circulation urbaine." },
    { name: "Émilie", role: "Monitrice permis B", bio: "Spécialiste des conduites accompagnées et de la boîte auto." },
    { name: "Anthony", role: "Moniteur", bio: "Le coach des permis accélérés." },
  ],

  nearbyCities: [
    { name: "Annemasse", slug: "annemasse", km: 1, intro: "Au cœur d'Annemasse, à 5 minutes à pied de la gare, l'Auto-École des Glières forme les Annemassiens depuis 2017 sur tous les permis : B, boîte auto, moto A2 et code en ligne.", highlights: ["Locaux au cœur d'Annemasse — 33 rue des Glières", "Connaissance fine des zones d'examen locales", "Formation accélérée disponible", "Code en salle 2x/semaine", "Suivi pédagogique digital", "Accompagnement CPF & permis 1€/jour"] },
    { name: "Ambilly", slug: "ambilly", km: 5, intro: "À 5 minutes d'Ambilly, l'Auto-École des Glières accueille de nombreux élèves Ambillaires.", highlights: ["5 min en voiture depuis Ambilly", "Bus direct vers nos locaux", "Examens à Annemasse, secteur connu", "Conduites pratiques sur ton trajet domicile-école"] },
    { name: "Gaillard", slug: "gaillard", km: 8, intro: "L'Auto-École des Glières est à 8 minutes de Gaillard.", highlights: ["8 min en voiture depuis Gaillard", "Examens dans le secteur Annemasse", "Permis Moto A2 disponible (nouveauté 2026)", "Code en ligne accessible 24/7"] },
    { name: "Ville-la-Grand", slug: "ville-la-grand", km: 6, intro: "À 6 minutes de Ville-la-Grand, l'Auto-École des Glières accueille de nombreux élèves de la commune.", highlights: ["6 min en voiture depuis Ville-la-Grand", "Tous les permis : B, auto, moto A2", "Conduite accompagnée dès 15 ans", "Forfait code 6 mois à 290€"] },
    { name: "Vétraz-Monthoux", slug: "vetraz-monthoux", km: 10, intro: "L'Auto-École des Glières est à 10 minutes de Vétraz-Monthoux.", highlights: ["10 min en voiture depuis Vétraz-Monthoux", "Approche pédagogique personnalisée", "Examens connus dans le secteur", "Financement CPF & permis 1€/jour"] },
  ],

  reviews: [
    { id: "r1", author: "Lucie M.", initials: "LM", date: "2026-04-12", rating: 5, formation: "Permis B", text: "Permis obtenu du premier coup grâce à Vincent ! Équipe au top, super pédagogue, locaux propres et accueil parfait avec Eva. Je recommande à 100%.", reply: "Merci Lucie, fière de toi. Roule prudemment 🧡" },
    { id: "r2", author: "Jordan B.", initials: "JB", date: "2026-03-28", rating: 5, formation: "Conduite accompagnée", text: "J'ai fait l'AAC ici dès mes 15 ans. Trois ans plus tard, permis du premier coup. Sylvain est patient, l'ambiance est cool, on apprend vraiment." },
    { id: "r3", author: "Inès K.", initials: "IK", date: "2026-03-15", rating: 5, formation: "Permis boîte automatique", text: "J'avais peur de me lancer après 30 ans. Émilie m'a mise en confiance dès la première heure. Permis BEA en 2 mois, je revis !" },
    { id: "r4", author: "Mehdi T.", initials: "MT", date: "2026-02-22", rating: 5, formation: "Code de la route", text: "Plateforme code super claire, cours en salle utiles. J'ai eu 38/40 du premier coup." },
    { id: "r5", author: "Camille D.", initials: "CD", date: "2026-02-10", rating: 4, formation: "Permis B", text: "Très bonne auto-école, équipe sympa. Petit bémol sur le délai pour avoir une date d'examen mais ça vient surtout des préfectures." },
    { id: "r6", author: "Tom L.", initials: "TL", date: "2026-01-30", rating: 5, formation: "Permis B accéléré", text: "Permis en 4 semaines, mission accomplie. Anthony assure, dispo et carré. Merci à toute l'équipe !" },
    { id: "r7", author: "Sarah R.", initials: "SR", date: "2026-01-18", rating: 5, formation: "Permis B", text: "Ambiance familiale, suivi personnalisé, et surtout aucune mauvaise surprise sur la facture. Que du bonheur." },
    { id: "r8", author: "Yanis F.", initials: "YF", date: "2025-12-20", rating: 5, formation: "Conduite accompagnée", text: "Vincent a été génial avec mon fils. Pédagogie au top, beaucoup de bienveillance. Merci !" },
    { id: "r9", author: "Élodie P.", initials: "EP", date: "2025-12-05", rating: 5, formation: "Permis B", text: "Une auto-école qui prend vraiment le temps d'expliquer. Loin du modèle usine. Permis du premier coup, 21 ans après mon inscription manquée 😄" },
    { id: "r10", author: "Kevin H.", initials: "KH", date: "2025-11-22", rating: 5, formation: "Passerelle", text: "J'avais le BEA, je voulais passer manuelle. Passerelle 7h impeccable avec Émilie, attestation reçue dans la foulée." },
  ],

  reviewStats: { average: 4.8, total: 412, distribution: { 5: 372, 4: 28, 3: 7, 2: 3, 1: 2 } },

  faq: [
    { category: "Inscription", q: "À partir de quel âge je peux m'inscrire ?", a: "Dès 15 ans pour la conduite accompagnée (AAC), 17 ans pour le permis B classique, 18 ans pour passer l'examen. Pour le permis AM cyclomoteur, c'est dès 14 ans." },
    { category: "Inscription", q: "Quels documents je dois fournir ?", a: "Pièce d'identité, 2 photos e-photo agréées, justificatif de domicile de moins de 3 mois, ASSR2 (si né après 1988), attestation de recensement (16-25 ans), et le permis si tu en as déjà un." },
    { category: "Inscription", q: "Combien de temps avant de pouvoir commencer ?", a: "Sous 48h après ton inscription. On te crée ton compte ANTS, on lance le dossier, et tu commences le code et les heures dans la foulée." },
    { category: "Tarifs", q: "Combien coûte le permis B chez vous ?", a: "Le forfait 20h démarre à 1 490 € (code + conduite + présentation à l'examen). On a aussi des formules 30h et accélérées. Aucun frais caché : tout est listé sur la page Tarifs." },
    { category: "Tarifs", q: "Le permis est-il finançable avec le CPF ?", a: "Oui, on est référencé Mon Compte Formation. Permis B, boîte auto, code, moto A2 et passerelle sont éligibles CPF." },
    { category: "Tarifs", q: "Vous proposez le permis à 1€ par jour ?", a: "Oui, pour les 15-25 ans. C'est un prêt à taux zéro de l'État qui te permet d'étaler le paiement. On t'aide à monter le dossier." },
    { category: "Code", q: "Comment je révise le code ?", a: "Tu as accès à une plateforme en ligne (web + mobile) avec plus de 1 000 questions officielles, des cours, des examens blancs. Et on a aussi des cours en salle 2 fois par semaine." },
    { category: "Code", q: "L'examen du code se passe où ?", a: "Dans un centre agréé La Poste, SGS ou Objectif Code. Tu choisis le créneau qui t'arrange. Coût de l'examen : 30 € (réglés au centre directement)." },
    { category: "Conduite", q: "Combien d'heures de conduite faut-il en moyenne ?", a: "La moyenne nationale est à 35h. Chez nous, le forfait 20h convient à la majorité, mais on te propose un forfait 30h ou des heures à la carte selon ton rythme." },
    { category: "Conduite", q: "Boîte manuelle ou boîte auto, je choisis quoi ?", a: "Boîte auto = formation plus courte (13h minimum), examen plus simple, mais tu ne pourras conduire que des voitures auto. Boîte manuelle = accès à toutes les voitures. Tu peux toujours passer la passerelle plus tard (7h)." },
    { category: "Conduite", q: "Vous avez la conduite accompagnée ?", a: "Oui, à partir de 15 ans. C'est statistiquement le meilleur moyen de réussir : 88% au premier passage. Tu commences ta formation, tu passes le code, puis tu roules avec un accompagnateur pendant minimum 1 an." },
    { category: "Examen", q: "Quel est votre taux de réussite ?", a: "75% de réussite au premier passage sur le permis B (vs 60% en moyenne nationale). 88% pour les conduites accompagnées." },
    { category: "Examen", q: "Si j'échoue, je dois tout repayer ?", a: "Non. Tu paies juste la représentation à l'examen (80 €) et éventuellement quelques heures complémentaires si nécessaire. Aucun forfait à racheter." },
    { category: "Pratique", q: "Vous êtes ouverts le samedi ?", a: "Oui, le samedi matin de 9h à 12h. Sinon du lundi au vendredi (horaires variables, voir la page Contact)." },
    { category: "Pratique", q: "Comment je récupère mon permis ?", a: "Le permis est expédié à ton domicile par lettre recommandée environ 3 semaines après l'examen. Tu reçois aussi un certificat provisoire valable 4 mois." },
    { category: "Handicap", q: "Vous accueillez les personnes en situation de handicap ?", a: "Oui. On a une procédure dédiée et un référent handicap. Selon le handicap, on peut adapter le véhicule ou orienter vers un partenaire spécialisé. Plus d'infos sur la page Accessibilité." },
  ],

  social: {
    google: "https://g.page/r/auto-ecole-glieres",
    instagram: "https://instagram.com/autoecole.glieres",
    facebook: "https://facebook.com/autoecoleglieres",
  },
};
